Options:
  #是否启用该配置组
  Enable: true
  #配置限定世界
  World:
    #是否启用
    Enable: true
    #世界名
    Info: "world"
  #配置限定权限
  Perm:
    #是否启用
    Enable: true
    #权限
    Info: "ce.perm.example"
  #配置掉落组
  Drop:
    #是否启用
    Enable: false
    #绑定掉落组
    Bind: Example
  #配置脚本动作
  Action:
    #在玩家死亡时运行
    Pre:
      #是否启用
      Enable: true
      #脚本
      Script: |-
        tell 'Pre Kether 运行成功'
        check 2 > 1
    #在玩家重生时运行
    Post:
      #是否启用
      Enable: true
      #脚本
      Script: |-
        tell 'Post Kether 运行成功'
  #配置玩家重生
  PlayerSpawn:
    #配置自动重生
    AutoRespawn:
      #是否启用
      Enable: true
      #延迟时间[单位s]
      Time: 1s
    #配置重生点
    Spawn:
      #重生地点类型[death:死亡点,coo：坐标, loc: 重生点]
      Type: death
      Info: 100 100 100 world
  #配置物品赎回
  ItemRedemption:
    #是否启用
    Enable: true
    #绑定赎回组
    Bind: Example





